#!/usr/bin/env Rscript

paths_file <- c("paths.R", file.path("code", "paths.R"))
source(paths_file[file.exists(paths_file)][1])

check_exact <- function(file, kind, needed_by, note = "") {
  path <- file.path(input_folder, file)
  data.frame(
    status = if (file.exists(path)) "OK" else "MISSING",
    kind = kind,
    file_or_pattern = file,
    needed_by = needed_by,
    note = note,
    stringsAsFactors = FALSE
  )
}

check_pattern <- function(pattern, kind, needed_by, note = "") {
  hits <- list.files(input_folder, pattern = pattern, full.names = FALSE)
  data.frame(
    status = if (length(hits)) "OK" else "MISSING",
    kind = kind,
    file_or_pattern = pattern,
    needed_by = needed_by,
    note = if (length(hits)) paste(hits, collapse = "; ") else note,
    stringsAsFactors = FALSE
  )
}

checks <- rbind(
  check_exact(
    "dataset_from_matlab.csv",
    "external/raw",
    "01_prepare_flux_timeseries, 12_wind_rose, 03_meteorology_summary fallback metadata",
    "Copied already if present."
  ),
  check_pattern(
    "(?i)imerg.*30min.*\\.csv$",
    "external/raw",
    "03_meteorology_summary, 13_maps",
    "Copy the old IMERG 30-minute precipitation CSV into data/."
  ),
  check_exact(
    "panamazon_flux_sites.csv",
    "external/snapshot",
    "13_maps",
    "Shipped with the repository. Regenerate from https://panamazonflux.org/sites with code/update_panamazon_sites.R."
  ),
  check_exact(
    "all_known_flux_sites_map_export.csv",
    "external/snapshot",
    "zz_build_zenodo_deposit (Fig 1 site layer, staged into the data deposit)",
    "Shipped with the repository."
  ),
  check_pattern(
    "^worldclim$",
    "external/optional",
    "13_maps (Fig 1 basemap)",
    "Not redistributable. code/13_maps.R downloads it via geodata::worldclim_global() if absent."
  ),
  check_exact(
    "dataset_from_matlab_with_ENSO_season_NEEok_Reco_GEP.csv",
    "derived",
    "02_resample_anova, 04_diel_cycles_carbon_balance",
    "Generated by 01_prepare_flux_timeseries."
  ),
  check_exact(
    "enso_conditions_data.RData",
    "derived",
    "03_meteorology_summary, 13_maps",
    "Generated by 02_resample_anova."
  ),
  check_exact(
    "tambopata_monthly_diurnal_sum_gC_m2_day.csv",
    "derived",
    "01_prepare_flux_timeseries monthly C-balance panel",
    "Generated by 01_prepare_flux_timeseries if missing."
  ),
  check_exact(
    "tambopata_48points_per_month.csv",
    "derived",
    "05_light_response_curves, 09_temperature_vpd_swc_bins, 10_surface_conductance, 11_nee_vs_soil_moisture_temperature",
    "Generated by 04_diel_cycles_carbon_balance."
  ),
  check_exact(
    "tambopata_48points_per_month_measured.csv",
    "derived",
    "05_light_response_curves, 09_temperature_vpd_swc_bins, 11_nee_vs_soil_moisture_temperature, 26, 27 (Figs 4, 5, 6, S14-S16, S18)",
    "Generated by 01b_build_measured_composite."
  ),
  check_exact(
    "light_response_mean_env_and_fit_params_by_year_with_Ts.csv",
    "derived",
    "07_light_response_parameter_highlights, 08_light_response_residual_highlights, 06_lmm_light_response_params",
    "Generated by 03_meteorology_summary; includes Ts and P2000."
  )
)

print(checks, row.names = FALSE)

missing <- checks[checks$status == "MISSING", ]

cat("\nSummary:\n")
cat("  OK:", sum(checks$status == "OK"), "\n")
cat("  Missing:", nrow(missing), "\n")

if (nrow(missing)) {
  cat("\nSee DATA.md for where each external input comes from.\n")
  cat("\nFiles/patterns to add or regenerate:\n")
  for (i in seq_len(nrow(missing))) {
    cat(
      "  - ", missing$file_or_pattern[[i]],
      " [", missing$kind[[i]], "]",
      " -> ", missing$needed_by[[i]],
      "\n    ", missing$note[[i]], "\n",
      sep = ""
    )
  }
}
